// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using System.Collections.Generic;


/// <summary>
/// Don't use this class directly.
/// Instead, instantiate an ALGUIDGenerator object and use that class.
/// That class calls this class' methods.
/// 
/// This prevents clients from being dependent on a static implementation of GUI generation.
/// If a new GUI generation implementation is needed, the change need only take place inside ALGUIDGenerator
/// </summary>
	public static class ALGUID
	{
		private static int next = 0;
		private static List<Int32> used = new List<Int32>();

		public static int Next()
		{
			int guid = next;
			next++;
			return guid;
		}

		public static bool isUsed(int val)
		{
			return used.Contains(val);
		}

		private static void claim(int val)
		{
			used.Add(val);
		}
	}


