// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
namespace AssemblyCSharp
{
		public class GenomeConstants
		{
			public static int NumGenes
		{
			get
			{
				return 6;
			}
		}


		public static int MinGeneValue
		{
			get
			{
				return 0;
			}
		}

		public static int MaxGeneValue
		{
			get
			{
				return 9;
			}
		}
		}
}

