// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using GeneticAlgorithms;
namespace AssemblyCSharp
{
		public interface IIndexedPopulation : IPopulation
		{
		IIndividual find(int key);
		bool containsKey(int key);
		void add(int key, IIndividual newIndividual);
        void Remove(int key);
		}
}

