// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using GeneticAlgorithms;

	public class LifeAgentIndividual : IIndividual
	{
		IGenome genome;
		ITraits traits;
		private IGeneToTraitMap traitMap;
		private int id;

		public LifeAgentIndividual(IGenome genome, IGeneToTraitMap geneToTraitMap, int id)
		{
			this.traitMap = geneToTraitMap;
			this.genome = genome;
			this.traits = geneToTraitMap.generateTraits(genome);
			this.id = id;
		}

        public LifeAgentIndividual(){}

		public int Id {
			get {
				return id;
			}
		}

      
      

		public Traits getTraits()
		{
			return (Traits)this.traits;
		}

		public IGenome getGenome()
		{
			return genome;
		}

		public IIndividual Clone()
		{
			LifeAgentIndividual lai = new LifeAgentIndividual(this.genome.Clone(), this.traitMap, this.id);
			return lai;
		}
	}


