// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using GeneticAlgorithms;

namespace AssemblyCSharp
{
	public class SingleIntegerGenomeFactory : IGenomeFactory
	{
		public IGenome construct(IGene[] genes)
		{
			int[] values = new int[genes.Length];
			for(int i=0; i<genes.Length; i++)
			{
				int v = (Int32)genes[i].getGeneticInformation();
				values[i] = v;
			}
			IGenome genome = new SingleIntegerGenome(values);
			return genome;
		}
	
		public IGenome constructRandom(IGeneFactory geneFactory, int size)
		{
			IGene[] genes = new IGene[size];
			for(int i=0; i<size; i++)
			{
				genes[i] = geneFactory.constructRandom();


			}
			return this.construct(genes);
		}
	}
}

