// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
using AssemblyCSharp;
namespace GeneticAlgorithms
{
	public class Traits : ITraits
	{

		public Traits (float speed, float perceptionRadius, float maxLifespan, int resourcesNeeded, int matePreferenceValue, StrategyType pathfindingStrategy)
		{
			this.speed = speed;
			this.perceptionRadius = perceptionRadius;
			this.maxLifespan = maxLifespan;
			this.resourcesNeeded = resourcesNeeded;
			this.matePreferenceValue = matePreferenceValue;
			this.pathfindingStrategy = pathfindingStrategy;
            this.intelligence = 10;
			this.Diet = AgentDietType.Herbivore;
		}

        public Traits (float speed, float perceptionRadius, float maxLifespan, int resourcesNeeded, int matePreferenceValue, int intelligence)
        {
            this.speed = speed;
            this.perceptionRadius = perceptionRadius;
            this.maxLifespan = maxLifespan;
            this.resourcesNeeded = resourcesNeeded;
            this.matePreferenceValue = matePreferenceValue;
            this.pathfindingStrategy = StrategyType.Naive;
            this.intelligence = intelligence;
			this.Diet = AgentDietType.Herbivore;
        }

		public Traits (float speed, float perceptionRadius, float maxLifespan, int resourcesNeeded, int matePreferenceValue, int intelligence, AgentDietType diet)
		{
			this.speed = speed;
			this.perceptionRadius = perceptionRadius;
			this.maxLifespan = maxLifespan;
			this.resourcesNeeded = resourcesNeeded;
			this.matePreferenceValue = matePreferenceValue;
			this.pathfindingStrategy = StrategyType.Naive;
			this.intelligence = intelligence;
			this.Diet = diet;
		}
		public Traits()
		{

		}

		private AgentDietType diet;
		private float speed;
		private float perceptionRadius;
		private float maxLifespan;
		private int resourcesNeeded;
		private int matePreferenceValue;
		private StrategyType pathfindingStrategy;
        private int intelligence;

		public float Speed {
			get {
				return speed;
			}
			set {
				speed = value;
			}
		}

		public float PerceptionRadius {
			get {
				return perceptionRadius;
			}
			set {
				perceptionRadius = value;
			}
		}

		public float MaxLifespan {
			get {
				return maxLifespan;
			}
			set {
				maxLifespan = value;
			}
		}

		public int ResourcesNeeded {
			get {
				return resourcesNeeded;
			}
			set {
				resourcesNeeded = value;
			}
		}

		public int MatePreferenceValue {
			get {
				return matePreferenceValue;
			}
			set {
				matePreferenceValue = value;
			}
		}

		public StrategyType PathfindingStrategy {
			get {
				return pathfindingStrategy;
			}
			set {
				pathfindingStrategy = value;
			}
		}

		public AgentDietType Diet {
			get {
				return diet;
			}
			set {
				diet = value;
			}
		}

        public int Intelligence {
            get{
                return intelligence;
            }
            set
            {
                this.intelligence = value;
            }
        }
	}
}

