// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
namespace AssemblyCSharp
{
	public class TraitConstants
	{
		public static int BaseSpeed
		{
			get 
			{
				return 5;
			}
		}

		public static int BasePerceptionRadius
		{
			get 
			{
				return 10;
			}
		}


		public static int BaseResourcesNeeded
		{
			get 
			{
				return 5;
			}
		}

		public static int MaxGeneValue
		{
			get 
			{
				return GenomeConstants.MaxGeneValue;
			}
		}

		public static float BaseLifeSpan
		{
			get
			{
				float numMinutes = 2f;
				return 60*numMinutes;
			}
		}
	}
}

