// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;
namespace GeneticAlgorithms
{
		public enum TraitIndex
		{
			Speed = 0,
			PerceptionRadius = 1,
			MaxLifespan = 2,
			RequiredResources = 3,
			PreferencePitch = 4,
			PathfindingStrategy = 5,
		}
}

